[serve]
# The address to serve on LAN.
address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 3000

[[proxy]]
# proxy /api/v1 to backend api
backend = "http://localhost:8000/api/v1"
